--CREATE TABLE Suppliers
--(
--	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
--	[Name] NVARCHAR(100) NOT NULL
--)

--CREATE TABLE GoodsTypes
--(
--    [Id] INT PRIMARY KEY IDENTITY NOT NULL,
--	[Name] NVARCHAR(100) NOT NULL
--)

--CREATE TABLE Goods
--(
--	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
--	[Name] NVARCHAR(100) NOT NULL,
--	GoodsTypeId INT FOREIGN KEY REFERENCES GoodsTypes(Id) NOT NULL,
--	Cost Money NOT NULL
--)

--CREATE TABLE Deliveries
--(
--	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
--	Amount INT NOT NULL,
--	DeliveryDate DATETIME2 NOT NULL,
--	GoodsId INT FOREIGN KEY REFERENCES Goods(Id) NOT NULL,
--	SupplierId INT FOREIGN KEY REFERENCES Suppliers(Id) NOT NULL
--)